-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 21:27:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
 
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
 
-- -----------------------------------------------------
-- Schema dbDecoU
-- -----------------------------------------------------
 
-- -----------------------------------------------------
-- Schema dbDecoU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbDecoU` DEFAULT CHARACTER SET utf8 ;
USE `dbDecoU` ;
 
-- -----------------------------------------------------
-- Table `dbDecoU`.`tblCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbDecoU`.`tblCategoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `dbDecoU`.`tblPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbDecoU`.`tblPersona` (
  `identificacion` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `tipoPersona` VARCHAR(1) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`identificacion`),
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC) )
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `dbDecoU`.`tblProveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbDecoU`.`tblProveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(20) NOT NULL,
  `nombreEmpresa` VARCHAR(45) NULL,
  PRIMARY KEY (`idProveedor`),
  INDEX `fk_persona_trabajador_idx` (`identificacion` ASC) ,
  CONSTRAINT `fk_persona_trabajador`
    FOREIGN KEY (`identificacion`)
    REFERENCES `dbDecoU`.`tblPersona` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `dbDecoU`.`tblProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbDecoU`.`tblProducto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `precioCompra` DECIMAL(7,2) NOT NULL,
  `precioVenta` DECIMAL(7,2) NOT NULL,
  `iva` DECIMAL(7,2) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_categoria_producto_idx` (`idCategoria` ASC) ,
  CONSTRAINT `fk_categoria_producto`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `dbDecoU`.`tblCategoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `dbDecoU`.`tblProveedorProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbDecoU`.`tblProveedorProducto` (
  `idProveedor` INT NOT NULL,
  `idProducto` INT NOT NULL,
  INDEX `fk_proveedor_producto_idx` (`idProveedor` ASC) ,
  INDEX `fk_producto_proveedor_idx` (`idProducto` ASC) ,
  CONSTRAINT `fk_proveedor_producto`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `dbDecoU`.`tblProveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_proveedor`
    FOREIGN KEY (`idProducto`)
    REFERENCES `dbDecoU`.`tblProducto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = ' ';
 
 
-- -----------------------------------------------------
-- Table `dbDecoU`.`tblEmpleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbDecoU`.`tblEmpleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(20) NOT NULL,
  `login` VARCHAR(13) NOT NULL,
  `cargo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_persona_empleado_idx` (`identificacion` ASC) ,
  CONSTRAINT `fk_persona_empleado`
    FOREIGN KEY (`identificacion`)
    REFERENCES `dbDecoU`.`tblPersona` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `dbDecoU`.`tblVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbDecoU`.`tblVenta` (
  `numeroFactura` INT NOT NULL AUTO_INCREMENT,
  `idEmpleado` INT NOT NULL,
  `total` DECIMAL(7,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `cedulaCliente` VARCHAR(20) NOT NULL,
  `tipoVenta` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`numeroFactura`),
  INDEX `fk_empleado_venta_idx` (`idEmpleado` ASC) ,
  CONSTRAINT `fk_empleado_venta`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `dbDecoU`.`tblEmpleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `dbDecoU`.`tblDetalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbDecoU`.`tblDetalleVenta` (
  `idDetalleFactura` INT NOT NULL AUTO_INCREMENT,
  `numFactura` INT NOT NULL,
  `codigoArticulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idDetalleFactura`),
  INDEX `fk_venta_detalleventa_idx` (`numFactura` ASC) ,
  CONSTRAINT `fk_venta_detalleventa`
    FOREIGN KEY (`numFactura`)
    REFERENCES `dbDecoU`.`tblVenta` (`numeroFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `dbDecoU`.`tblCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbDecoU`.`tblCredito` (
  `idCredito` INT NOT NULL AUTO_INCREMENT,
  `numFactura` INT NOT NULL,
  `numeroCuotas` INT NOT NULL,
  `valorCuota` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `referencia1` VARCHAR(50) NOT NULL,
  `referencia2` VARCHAR(50) NOT NULL,
  `caducidad` DATE NOT NULL,
  `consideraciones` VARCHAR(45) NULL,
  PRIMARY KEY (`idCredito`),
  INDEX `fk_venta_credito_idx` (`numFactura` ASC) ,
  CONSTRAINT `fk_venta_credito`
    FOREIGN KEY (`numFactura`)
    REFERENCES `dbDecoU`.`tblVenta` (`numeroFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `dbDecoU`.`tblAbono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbDecoU`.`tblAbono` (
  `idAbono` INT NOT NULL AUTO_INCREMENT,
  `idCredito` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `valorAbono` DECIMAL(7,2) NOT NULL,
  `numCuota` INT NOT NULL,
  `notaCobranza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAbono`),
  INDEX `fk_credito_detallecredito_idx` (`idCredito` ASC) ,
  CONSTRAINT `fk_credito_detallecredito`
    FOREIGN KEY (`idCredito`)
    REFERENCES `dbDecoU`.`tblCredito` (`idCredito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `dbDecoU`.`tblCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbDecoU`.`tblCliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(20) NOT NULL,
  `historial` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_persona_cliente_idx` (`identificacion` ASC) ,
  CONSTRAINT `fk_persona_cliente`
    FOREIGN KEY (`identificacion`)
    REFERENCES `dbDecoU`.`tblPersona` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;