/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import logica.PEmpleado;

/**
 *
 * @author Edwin
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public FrmInicio() {
        initComponents();
        this.setExtendedState(FrmInicio.MAXIMIZED_BOTH);
        this.setTitle("SISTEMA DE FACTURACION DECO-U             "+ PEmpleado.usuario[2]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuPersonas = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenuItem();
        menuEmpleado = new javax.swing.JMenuItem();
        menuProveedor = new javax.swing.JMenuItem();
        menuArticulos = new javax.swing.JMenu();
        menuCategorias = new javax.swing.JMenuItem();
        menuStock = new javax.swing.JMenuItem();
        menuArticulo = new javax.swing.JMenuItem();
        menuFacturacion = new javax.swing.JMenu();
        menuVentas = new javax.swing.JMenuItem();
        menuCreditos = new javax.swing.JMenuItem();
        menuAbonos = new javax.swing.JMenuItem();
        menuInformes = new javax.swing.JMenu();
        MenuInformeCobro = new javax.swing.JMenuItem();
        menuHistorialFactura = new javax.swing.JMenuItem();
        menuInformeCreditos = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuAcerca = new javax.swing.JMenuItem();
        menuAyudas = new javax.swing.JMenuItem();
        menuMora = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(204, 255, 255));

        menuPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/home.png"))); // NOI18N
        menuPersonas.setMnemonic('f');
        menuPersonas.setText("Personas");

        menuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/user-business.png"))); // NOI18N
        menuCliente.setMnemonic('c');
        menuCliente.setText("Clientes");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        menuPersonas.add(menuCliente);

        menuEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/user-worker.png"))); // NOI18N
        menuEmpleado.setText("Empleados");
        menuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoActionPerformed(evt);
            }
        });
        menuPersonas.add(menuEmpleado);

        menuProveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/truck.png"))); // NOI18N
        menuProveedor.setText("Proveedores");
        menuProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProveedorActionPerformed(evt);
            }
        });
        menuPersonas.add(menuProveedor);

        menuBar.add(menuPersonas);

        menuArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/blue-folders-stack.png"))); // NOI18N
        menuArticulos.setMnemonic('e');
        menuArticulos.setText("Articulos");

        menuCategorias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menuCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/drive--pencil.png"))); // NOI18N
        menuCategorias.setMnemonic('t');
        menuCategorias.setText("Categorias");
        menuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriasActionPerformed(evt);
            }
        });
        menuArticulos.add(menuCategorias);

        menuStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/store.png"))); // NOI18N
        menuStock.setMnemonic('y');
        menuStock.setText("Stock");
        menuStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStockActionPerformed(evt);
            }
        });
        menuArticulos.add(menuStock);

        menuArticulo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/wrench-screwdriver.png"))); // NOI18N
        menuArticulo.setText("Articulos");
        menuArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArticuloActionPerformed(evt);
            }
        });
        menuArticulos.add(menuArticulo);

        menuBar.add(menuArticulos);

        menuFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/pencil--plus.png"))); // NOI18N
        menuFacturacion.setMnemonic('h');
        menuFacturacion.setText("Facturacion");

        menuVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/currency.png"))); // NOI18N
        menuVentas.setMnemonic('c');
        menuVentas.setText("Ventas");
        menuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasActionPerformed(evt);
            }
        });
        menuFacturacion.add(menuVentas);

        menuCreditos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/credit-card--plus.png"))); // NOI18N
        menuCreditos.setMnemonic('a');
        menuCreditos.setText("Creditos");
        menuCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreditosActionPerformed(evt);
            }
        });
        menuFacturacion.add(menuCreditos);

        menuAbonos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        menuAbonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/pencil--plus.png"))); // NOI18N
        menuAbonos.setText("Abonos");
        menuAbonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbonosActionPerformed(evt);
            }
        });
        menuFacturacion.add(menuAbonos);

        menuBar.add(menuFacturacion);

        menuInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/information-button.png"))); // NOI18N
        menuInformes.setText("Informes");

        MenuInformeCobro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/money--exclamation.png"))); // NOI18N
        MenuInformeCobro.setText("De cobro");
        MenuInformeCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInformeCobroActionPerformed(evt);
            }
        });
        menuInformes.add(MenuInformeCobro);

        menuHistorialFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/book--exclamation.png"))); // NOI18N
        menuHistorialFactura.setText("De facturas");
        menuInformes.add(menuHistorialFactura);

        menuInformeCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/credit-card--exclamation.png"))); // NOI18N
        menuInformeCreditos.setText("De creditos");
        menuInformes.add(menuInformeCreditos);

        menuBar.add(menuInformes);

        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/book-question.png"))); // NOI18N
        menuAyuda.setText("Ayuda");

        menuAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuAcerca.setText("Acerca de...");
        menuAyuda.add(menuAcerca);

        menuAyudas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menuAyudas.setText("Ayuda");
        menuAyuda.add(menuAyudas);

        menuBar.add(menuAyuda);

        menuMora.setText("Mora");

        jMenuItem1.setText("Mora");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuMora.add(jMenuItem1);

        menuBar.add(menuMora);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 1473, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriasActionPerformed
        // TODO add your handling code here:
        FrmCategoria form = new FrmCategoria();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_menuCategoriasActionPerformed

    private void menuStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStockActionPerformed
        // TODO add your handling code here:
//        FrmAlertaCobro form = new FrmAlertaCobro();
//        escritorio.add(form);
//        form.toFront();
//        form.setVisible(true);
    }//GEN-LAST:event_menuStockActionPerformed

    private void menuCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreditosActionPerformed
        // TODO add your handling code here:
        FrmFacturacion form = new FrmFacturacion();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuCreditosActionPerformed

    private void menuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasActionPerformed
        // TODO add your handling code here:
        FrmFacturacion form = new FrmFacturacion();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);/*
        frmReserva.txtIdTrabajador.setText(lblIdpersona.getText());
        frmReserva.txtTrabajador.setText(lblNombre.getText() + " " + lblApaterno.getText());
        frmReserva.idusuario = Integer.parseInt(lblIdpersona.getText());*/
                
    }//GEN-LAST:event_menuVentasActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        // TODO add your handling code here:
        FrmCliente form = new FrmCliente();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoActionPerformed
        // TODO add your handling code here:
        FrmEmpleado form = new FrmEmpleado();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuEmpleadoActionPerformed

    private void menuProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProveedorActionPerformed
        // TODO add your handling code here:
        FrmProveedor form = new FrmProveedor();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuProveedorActionPerformed

    private void menuAbonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbonosActionPerformed
        // TODO add your handling code here:
        FrmAbonar form = new FrmAbonar();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuAbonosActionPerformed

    private void menuArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArticuloActionPerformed
        // TODO add your handling code here:
        FrmProducto form = new FrmProducto();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuArticuloActionPerformed

    private void MenuInformeCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInformeCobroActionPerformed
        // TODO add your handling code here:
        FrmAlertaCobro form = new FrmAlertaCobro();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_MenuInformeCobroActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FrmMora form = new FrmMora();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuInformeCobro;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuAbonos;
    private javax.swing.JMenuItem menuAcerca;
    private javax.swing.JMenuItem menuArticulo;
    public static javax.swing.JMenu menuArticulos;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuItem menuAyudas;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuCategorias;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuCreditos;
    private javax.swing.JMenuItem menuEmpleado;
    private javax.swing.JMenu menuFacturacion;
    private javax.swing.JMenuItem menuHistorialFactura;
    private javax.swing.JMenuItem menuInformeCreditos;
    private javax.swing.JMenu menuInformes;
    private javax.swing.JMenu menuMora;
    private javax.swing.JMenu menuPersonas;
    private javax.swing.JMenuItem menuProveedor;
    private javax.swing.JMenuItem menuStock;
    private javax.swing.JMenuItem menuVentas;
    // End of variables declaration//GEN-END:variables

}
